### ISSUE TITLE
i do not know where to find the csv

### ISSUE THREAD

**Issue by gaodianzhuo** [kiefersmith/House-Search-v2#1]
apex <- read_csv("apex2.csv")
cary <- read_csv("cary2.csv")
raleigh <- read_csv("raleigh.csv")

**Comment by kiefersmith** [comment]
Hey!  Thank you for taking the time to check out the app and code.  Unfortunately, I am not able to offer the data for download, as it is subject to data security standards by the organization I downloaded it from (my local MLS).  If you email me I can send you a snapshot so that you can get an idea of the data structure.

Thanks again,

Kiefer
